### PR TITLE
Use common memcached.GetMemcachedServerListWithInetString()

### PR DESCRIPTION
**Pull request by stuggi**
Use common func to retrieve the memcached server list for a memcached instance.

### CODE REVIEW

**Comment by abays** [comment]
> @stuggi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/swift-operator-build-deploy-kuttl 	[76aec54](https://github.com/openstack-k8s-operators/swift-operator/commit/76aec54b3773457655a929f9d505a86ad4aa4b7c) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_swift-operator/169/pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl/1767229796531572736) 	true 	`/test swift-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=swift-operator&pr=169). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:stuggi).

Failure looks like it could indeed be related to the PR:

```
case.go:366: resource Swift:swift-kuttl-tests/swift: .status.conditions.message: value mismatch, expected: Setup complete != actual:  Memcached instance has not been provisioned
```

**Comment by abays** [comment]
> > @stuggi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/swift-operator-build-deploy-kuttl 	[76aec54](https://github.com/openstack-k8s-operators/swift-operator/commit/76aec54b3773457655a929f9d505a86ad4aa4b7c) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_swift-operator/169/pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl/1767229796531572736) 	true 	`/test swift-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=swift-operator&pr=169). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:stuggi).
> 
> Failure looks like it could indeed be related to the PR:
> 
> ```
> case.go:366: resource Swift:swift-kuttl-tests/swift: .status.conditions.message: value mismatch, expected: Setup complete != actual:  Memcached instance has not been provisioned
> ```

Ah nope, it's the missing hashes issue affecting all repos:

```
 Warning  Failed          23m (x4 over 24m)     kubelet            Failed to pull image "quay.io/podified-antelope-centos9/openstack-memcached@sha256:8347d7e59d00117771cdc68c39c2ccebcfb6dbd197689bd2231a1e9fd8fb44c6": rpc error: code = Unknown desc = reading manifest sha256:8347d7e59d00117771cdc68c39c2ccebcfb6dbd197689bd2231a1e9fd8fb44c6 in quay.io/podified-antelope-centos9/openstack-memcached: manifest unknown
 ```

**Review by cschwede — APPROVED** [review]
/lgtm

**Pull request merged**
