### PR TITLE
[tlse] tls for SwiftProxy pod configuration

### PR DESCRIPTION
**Pull request by stuggi**
Public/Internal service cert secrets and the CA bundle secret can be passed to configure httpd virtual hosts for tls termination. The certs get direct mounted to the appropriate place in etc/pki/tls/certs/%s.crt|key and a CA bundle to
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem . Job deployments for bootstrap/cron get the CA bundle added if configured.

Also indexes the named input resources for password, CA bundle, and endpoint secrets to be able to watch them for any changes and reconcile if needed.

Note: Atm the CA bundle is not being attached to SwiftStorage or SwiftRing deployments.

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/428

Jira: [OSPRH-4371](https://issues.redhat.com//browse/OSPRH-4371)

### CODE REVIEW

**Comment by stuggi** [comment]
```
sh-5.1$ openstack endpoint list --service swift
+----------------------------------+-----------+--------------+--------------+---------+-----------+-----------------------------------------------------------------------+
| ID                               | Region    | Service Name | Service Type | Enabled | Interface | URL                                                                   |
+----------------------------------+-----------+--------------+--------------+---------+-----------+-----------------------------------------------------------------------+
| 33f1667560a84b7bb3fe4427c7e2a38c | regionOne | swift        | object-store | True    | internal  | https://swift-internal.openstack.svc:8080/v1/AUTH_%(tenant_id)s       |
| c5f8ce1a26aa44768b50368f1a2f99a6 | regionOne | swift        | object-store | True    | public    | https://swift-public-openstack.apps-crc.testing/v1/AUTH_%(tenant_id)s |
+----------------------------------+-----------+--------------+--------------+---------+-----------+-----------------------------------------------------------------------+


sh-5.1$ openstack container create test
+---------------------------------------+-----------+------------------------------------+
| account                               | container | x-trans-id                         |
+---------------------------------------+-----------+------------------------------------+
| AUTH_fd622b46816441a29b07c3942c2de510 | test      | txfe7f44c192d24242805c1-0065bcee83 |
+---------------------------------------+-----------+------------------------------------+

sh-5.1$ openstack object create test /etc/hosts
+------------+-----------+----------------------------------+
| object     | container | etag                             |
+------------+-----------+----------------------------------+
| /etc/hosts | test      | 8e3d8eb4cbfcca2782b82c8d1b742a2b |
+------------+-----------+----------------------------------+

sh-5.1$ openstack object list test
+-----------+
| Name      |
+-----------+
| etc/hosts |
+-----------+
```

**Comment by stuggi** [comment]
Note, I have also update the SwiftProxy controller to use defer to update its status and metadata like other operators and added more conditions

**Comment by stuggi** [comment]
envtest like we did in the other operators are currently not part of this PR. those should be added when general envtests get added to the swift operator.

**Review by cschwede — APPROVED** [review]
/lgtm

Tested, worked fine and requests are passed through Apache:

[crc@osp-storage-06 install_yamls]$ oc logs -c proxy-httpd swift-proxy-6b99cbc54f-mlpbx | grep -v healthcheck
10.217.0.1 - - [02/Feb/2024:15:37:10 +0000] "PUT /v1/AUTH_d50174674be94475ac6690146fcd76e8/test HTTP/1.1" 201 - "-" "openstacksdk/1.0.1 keystoneauth1/5.1.2 python-requests/2.25.1 CPython/3.9.18"
10.217.0.1 - - [02/Feb/2024:15:37:22 +0000] "PUT /v1/AUTH_d50174674be94475ac6690146fcd76e8/test/obj HTTP/1.1" 201 - "-" "openstacksdk/1.0.1 keystoneauth1/5.1.2 python-requests/2.25.1 CPython/3.9.18"
10.217.0.1 - - [02/Feb/2024:15:38:15 +0000] "GET /v1/AUTH_d50174674be94475ac6690146fcd76e8/test/obj HTTP/1.1" 200 - "-" "openstacksdk/1.0.1 keystoneauth1/5.1.2 python-requests/2.25.1 CPython/3.9.18"

Minor nit inline, but I'm fine with this. 

Thanks for fixing additional thinks like conditions etc.!

**Pull request merged**
