### PR TITLE
Update tls cert secret validation due VerifyCertSecrets() change

### PR DESCRIPTION
**Pull request by stuggi**
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/559

Jira: [OSPRH-9991](https://issues.redhat.com//browse/OSPRH-9991)

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by cschwede** [comment]
/test swift-operator-build-deploy-kuttl

"failed to wait for the created cluster claim to become ready: timed out waiting for the condition"

**Comment by abays** [comment]
> @stuggi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/swift-operator-build-deploy-kuttl 	[5c2847a](https://github.com/openstack-k8s-operators/swift-operator/commit/5c2847a61df4c9012b77ab58f8d86a66cd9bd638) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_swift-operator/267/pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl/1832006136081944576) 	true 	`/test swift-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=swift-operator&pr=267). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:stuggi).

```
error: build error: Failed to push image: trying to reuse blob sha256:c0ca389759b542396e6b30afcb100a3823d3b343bc847eee7f60d609a106f674 at destination: pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": net/http: TLS handshake timeout
```

/test swift-operator-build-deploy-kuttl

**Comment by abays** [comment]
> @stuggi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/swift-operator-build-deploy-kuttl 	[5c2847a](https://github.com/openstack-k8s-operators/swift-operator/commit/5c2847a61df4c9012b77ab58f8d86a66cd9bd638) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_swift-operator/267/pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl/1832103388041449472) 	true 	`/test swift-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=swift-operator&pr=267). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:stuggi).

Okay, giving up on this for the week :laughing:

**Comment by cschwede** [comment]
The last failre looks valid - seems like the instance wasn't cleaned up before the next test, and thus failed.

I'm starting a local run with the same PR now and going to debug this.

**Comment by stuggi** [comment]
I think this is actually might be real based on a barbican sample which has node selectors which can not work in the kuttl tests. 

This is the barbican sample which gets installed https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_swift-operator/267/pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl/1832707416739811328/artifacts/swift-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-53665dcfd348b7c28dfa5f430f95a9db74c3865c8dd68ecfca671170ed60715f/namespaces/swift-kuttl-tests/crs/barbicans.barbican.openstack.org/barbican.yaml

The barbican pods fail to get scheduled like:
```
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  15m                    default-scheduler  0/3 nodes are available: 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  4m55s (x2 over 9m55s)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
```

There is a nodeselector specified, which can not be satisfied:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-09-08T09:48:41Z"
  generation: 1
  labels:
    component: barbican-api
    service: barbican
  name: barbican-api-api
  namespace: swift-kuttl-tests
  ownerReferences:
  - apiVersion: barbican.openstack.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: BarbicanAPI
    name: barbican-api
    uid: 1ce496a4-74b5-4786-9b8b-566bd02c9b18
  resourceVersion: "523678"
  uid: ea09e7fd-c565-4b43-9b37-ddb005075aad
spec:
...
      nodeSelector:
        optional_override: here
```

coming from https://github.com/openstack-k8s-operators/barbican-operator/blob/main/config/samples/barbican_v1beta1_barbican.yaml#L32-L33

The nodeselector in barbican sample is there since a longer time, but it was only enabled in the controller recently with https://github.com/openstack-k8s-operators/barbican-operator/pull/153 and the current dependency in swift maps just to before that commit. I think we have to update the barbican sample to remove the nodeSelectors which can not work in ci.

**Pull request merged**
