### PR TITLE
Configure Ceilometer middleware

### PR DESCRIPTION
**Pull request by cschwede**
The Ceilometer middleware sends notifications using RabbitMQ, thus creating a user and secret to configure the middleware.

### CODE REVIEW

**Comment by abays** [comment]
CI failure seems like it might be legitimate:

```
logger.go:42: 13:05:02 | basic-deploy_tls/1-deploy-swift | for: "../../../../config/samples/swift_v1beta1_swift_tls.yaml": error when patching "../../../../config/samples/swift_v1beta1_swift_tls.yaml": admission webhook "vswift.kb.io" denied the request: Swift.swift.openstack.org "swift" is forbidden: spec.swiftStorage.replicas: Invalid value: 1: SwiftStorage does not support scale-in
```

**Comment by cschwede** [comment]
> CI failure seems like it might be legitimate:
> 
> ```
> logger.go:42: 13:05:02 | basic-deploy_tls/1-deploy-swift | for: "../../../../config/samples/swift_v1beta1_swift_tls.yaml": error when patching "../../../../config/samples/swift_v1beta1_swift_tls.yaml": admission webhook "vswift.kb.io" denied the request: Swift.swift.openstack.org "swift" is forbidden: spec.swiftStorage.replicas: Invalid value: 1: SwiftStorage does not support scale-in
> ```

Yes, the actual issue was one type - I uppercased the template variable names to make them consistent, but forgot one:

https://github.com/openstack-k8s-operators/swift-operator/compare/7ae67c626d0681e57111857bf9a1b9112ed4dc41..bcae5144e582a49875435da75aef840aeb57ec25

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
