### PR TITLE
Regenerate go.mod indirect dependencies

### PR DESCRIPTION
**Pull request by gibizer**
During the golang version bump we unintentionally introduced a too new
indirect dependency on kube-openapi:

k8s.io/kube-openapi@v0.0.0-20240209001042-7a0d5b415232

This is not required by any of our direct deps and this is also a
version that required golang 1.21. If your system has golang 1.21
installed the this dependency might force go mod tidy to change the
golang version in the go.mod file to 1.21.

This patch removed all the indirect dependencies and let go mod tidy to
regenerate them to get rid of the too new kube-openapi version.

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
there might be an issue with ring job being rerun, but we could not reproduce it yet. lets rerun and see if we hit it again.

**Comment by stuggi** [comment]
@cschwede probably found the issue. if the pvc does not yet have the status bound, the capacity is empty, which is uses ad input at https://github.com/openstack-k8s-operators/swift-operator/blob/main/pkg/swiftring/funcs.go#L64

**Pull request merged**
